### ISSUE TITLE
".self" displays list of aaaa's

### ISSUE THREAD

**Issue by teameh** [Shopify/superdb#9]
Pretty weird issue, see screenshot.

The shell window gives me `>` instead of `iPhone Simulator: Debug Me >`

And when I type `.self {enter}` I get a scrollable list of a's...

Seen this before / any idea's ?

![superdb issue](https://f.cloud.github.com/assets/1330668/80169/8908022c-6227-11e2-9bcd-35dd9ffcf783.png)

**Comment by jbrennan** [comment]
Though it does make an awesome bug title, yeah that is sort of a bug. I've been working on a code completion menu, but it's not quite finished yet. I think you might be on an older commit where I hadn't yet disabled it (or you I commented the completion stuff).

Either way, it's best left off for now.

**Comment by jbrennan** [comment]
You might have been on master before I merged develop into it. I'd pull all branches from origin. That should fix it.

**Comment by teameh** [comment]
Weird, I seemed to have only cloned the `develop` branch..

I just cloned  with:`$ git  clone https://github.com/Shopify/superdb.git`

But `$ git branch` gives me:

```
$ git pull origin
    Already up-to-date.
$ git branch
    * develop
```

So I tried to clone the master branch with..

```
$ git  clone https://github.com/Shopify/superdb.git suberdb3 -b master 
```

But I still get the aaaa's.

I'm at commit <a href="https://github.com/Shopify/superdb/commit/1b04fb768154cda7bdbfc366e0f8d459fb0e2737">1b04fb768154cda7bdbfc366e0f8d459fb0e2737</a>

**Comment by jessearmand** [comment]
You can disable the suggestionWindowController here, but the shell doesn't seem to be working.

```
- (void)configureDisconnectedShell {
    self.prompt = @"> ";
    [self.shellView setInputHandler:^(NSString *input, JBShellView *sender) {

        NSMutableArray *array = [@[] mutableCopy];
        NSString *completion = @"a";
        for (NSInteger i = 0; i < 10; i++) {
            [array addObject:@{@"title" : completion}];
            completion = [completion stringByAppendingString:@"a"];
        }
//      [self.suggestionWindowController setSuggestions:array];
//      [self.suggestionWindowController beginForParentTextView:sender];

    }];
}
```

![Screen Shot 2013-01-22 at 12 19 10 PM](https://f.cloud.github.com/assets/67312/85293/eb38a724-644a-11e2-8a43-6c3c0c0d1c67.png)

**Comment by jbrennan** [comment]
As figured out in issue #10 this might be caused by pressing the Shell button (which is there for my testing) instead of attaching to a device. This is my bad for not including it in the readme. I'll try to get this fixed up soon, currently don't have access to Xcode.

**Comment by teameh** [comment]
oh.. yeah indeed, that seemed to be the problem. I figured you had to select the right application and then press the shell button instead of double-click on the application to attach it. I thought I tried everything but it seemed I didn't. Thanks for the reply.
